"""Layout builder: part numbering and stations (frames / bulkheads)."""
from __future__ import annotations

from .b_common import *  # noqa: F401,F403

PART_NUMBERS = {                       # module -> [first, last] number (disjoint across modules; any group code)
    "chassis": [1, 149], "wing": [150, 249], "tail": [250, 349], "shell": [350, 499], "propulsion": [500, 569],
    "fuel": [570, 619], "gear": [620, 719], "systems": [720, 819], "payload": [820, 869], "hardware": [870, 999]}

PART_NUMBERING = {
    "convention": "YK250-<CODE>-NNN[-L|-R]: CODE = group code (CH chassis, SH shell, WG wing, TL tail, FC flight "
                  "controls, PR propulsion, FU fuel, LG landing gear, SY systems, PL payload, HW hardware); NNN = "
                  "three-digit number from the range of the PRODUCING MODULE (layout.part_numbers, ranges disjoint "
                  "across modules, so a number is unique whatever the group code); -R starboard part modelled in "
                  "+y, -L its mirrored port copy (core.parts.mirror_part), no suffix on the centre line",
    "codes": {"chassis": "CH", "shell": "SH", "wing": "WG", "tail": "TL", "controls": "FC", "propulsion": "PR",
              "fuel": "FU", "gear": "LG", "systems": "SY", "payload": "PL", "hardware": "HW"},
    "modules": {
        "chassis": {"groups": ["chassis"], "sub_ranges": {"centre wing box and joint fittings": [1, 1],
                    "frames and bulkheads (stations)": [2, 19], "longerons, keel members, decks, walls": [20, 49],
                    "wing joint / glove ribs and fittings": [50, 69], "landing-gear fittings": [70, 84],
                    "engine mount and firewall": [85, 94], "tail fittings and stabilator bearings": [95, 109],
                    "turret, parachute, fuel and equipment supports": [110, 149]}},
        "wing": {"groups": ["wing", "controls"], "sub_ranges": {"outer panel structure": [150, 199],
                 "ailerons, flaps, hinges, actuators, linkages (FC)": [200, 249]}},
        "tail": {"groups": ["tail", "controls"], "sub_ranges": {"fins, stubs, ventral, stabilators": [250, 299],
                 "rudders, stabilator drives, hinges, linkages (FC)": [300, 349]}},
        "shell": {"groups": ["shell"], "sub_ranges": {"body skins and access panels": [350, 419],
                  "LERX/glove skins and wing-joint panels": [420, 449], "cowling and fairings": [450, 499]}},
        "propulsion": {"groups": ["propulsion"], "sub_ranges": {"engine, mount isolators, exhaust": [500, 539],
                       "propeller, spinner, cooling ducts and baffles": [540, 569]}},
        "fuel": {"groups": ["fuel"], "sub_ranges": {"cells, lines, valves, vents, filler, sensors": [570, 619]}},
        "gear": {"groups": ["gear", "controls"], "sub_ranges": {"legs, wheels, brakes, actuators": [620, 669],
                 "doors, hinges, locks, door drives": [670, 719]}},
        "systems": {"groups": ["systems"], "sub_ranges": {"avionics, power, harness": [720, 779],
                    "antennas, air data, lights, recovery": [780, 819]}},
        "payload": {"groups": ["payload"], "sub_ranges": {"EO/IR turret, elevator, bay doors": [820, 849],
                    "mission computer, payload tray": [850, 869]}},
        "hardware": {"groups": ["hardware"], "sub_ranges": {
            "fastener parts generated by hardware.py: YK250-HW-<fastener id> (fastener id = <owner part id>-<Bn|Pn|Cn>)":
                [0, 0], "stand-alone hardware items (keeper plates, shims, ballast plates)": [870, 999]}}},
    "notes": "Interface part ids below (layout.stations[*].part, chassis members, shell panels, mechanisms, systems) are "
             "fixed by this section; producers use them for parent/contacts and may add further numbers from their "
             "own range. root_part is the first part loaded in the assembly jig (centre wing box)."}


def notch(cid, purpose, y, z_bottom, cover):
    """Edge notch at the top of a frame (open to the frame edge under a removable cover): the web edge band and skin
    flange are interrupted on purpose (a bridle / spine passage that must lift out); a bonded U-doubler of solid laminate
    (16 plies PW, 3.2 mm, 20 mm wide) runs round the notch and carries the edge-band load past it (fix round 2, PK2-02:
    layout_check C02 checks the width, the cover and the doubler; pass-throughs are checked on their corners). The
    upper z bound 0.4 m means 'open to the frame edge'."""
    return {"id": cid, "purpose": purpose, "kind": "edge notch", "y": r3(y), "z": [r3(z_bottom), 0.4],
            "cover": cover, "doubler": "bonded U-doubler PW 16 plies (3.2 mm) x 20 mm round the notch, ends 25 mm "
                                       "past the notch corners into the edge band"}


def cut(cid, purpose, y, z, mirror=False, kind="pass-through"):
    d = {"id": cid, "purpose": purpose, "kind": kind, "y": r3(y), "z": r3(z)}
    if mirror:
        d["mirror"] = True
    return d


SANDWICH = {"material": "cfrp_pw_mtm45_as4", "process": "prepreg_ooa_vacbag", "layup": "rib_panel",
            "t": 0.0068, "construction": "CFRP PW 2 plies / ROHACELL 51 WF 6 mm / 2 plies (layups.rib_panel incl. "
                                         "inner plies), core ramped out (1:3) to a 1.6 mm solid laminate edge band "
                                         "20 mm wide at every fastener line and flange"}


def stations() -> list:
    zb0, zb1 = Z_BOX
    tb = ZP["turret_bay"]["box"]
    pb = ZP["parachute_bay"]["box"]
    pay = ZP["payload_bay"]["box"]
    mw = ZP["main_gear_wells"]["box"]
    nw = ZP["nose_gear_well"]["box"]
    eq = ZP["equipment_bay_aft"]["box"]
    st = []

    def add(sid, x, role, ftype, part, cutouts, inset=0.0065, sweep=0.0, ring_depth=None, mat=None, notes="",
            name_tr="", flange_w=0.028, ring_z_max=None):
        d = {"id": sid, "x": r3(x), "sweep_deg": r3(sweep, 3), "role": role, "role_tr": name_tr, "type": ftype,
             "part": part, "inset": inset}
        d.update(copy.deepcopy(mat or SANDWICH))
        d["flange_w"] = flange_w            # T-flange width each side of the web at the skin line (land of skins/panels)
        if ring_depth is not None:
            d["ring_depth"] = ring_depth
        if ring_z_max is not None:
            d["ring_z_max"] = ring_z_max
        d["cutouts"] = cutouts
        if notes:
            d["notes"] = notes
        st.append(d)

    add("FS0300", 0.300, "nose-cone bulkhead: nose-cone attach flange (8 x M4 nutplates), pitot/static and FTS "
        "antenna feed-throughs; closes the forward equipment bay", "bulkhead", "YK250-CH-002",
        [cut("C-PITOT", "pitot/static lines (2 x 6 mm tube, bulkhead unions)", [-0.012, 0.012], [-0.040, -0.016]),
         cut("C-COAX-NC", "coax feeds of the nose-cone antennas (C2-A, backup diversity, FTS) and the nose branch "
             "H-NOSE (fix round 2, PK2-02: on the centre line above the pitot lines, every corner >= inset + 20 mm edge "
             "band from the OML)", [-0.012, 0.012], [-0.004, 0.024])], name_tr="burun konisi perdesi")
    add("FS0600", 0.600, "nose-gear forward bulkhead: front of the keel walls and the chine longerons, forward "
        "wall of the nose-gear well, nose-gear down-lock stop", "bulkhead", "YK250-CH-003",
        [cut("C-HARN-FWD", "harness trunk to the forward bay (pitot, FTS, nose-cone coax), above the avionics deck",
             [0.045, 0.080], [0.020, 0.040])], name_tr="burun takımı ön perdesi")
    add("FS1110", 1.110, "turret-bay front bulkhead: aft end of the nose box (keel walls, avionics deck, side "
        "bays), aft wall of the nose-gear well; turret elevator rail front mounts", "bulkhead", "YK250-CH-004",
        [cut("C-HARN-1110", "main harness trunk H-MAIN (port, above the avionics deck; fix round 2, PK2-02: corners "
             ">= inset + 20 mm edge band from the V roof)", [-0.168, -0.118], [0.019, 0.051]),
         cut("C-COAX-1110", "coax trunk H-COAX (starboard, below the avionics deck from the side bay)", [0.125, 0.165],
             [-0.022, 0.012])], name_tr="taret bölmesi ön perdesi")
    add("FS1330", 1.330, "turret-bay aft bulkhead: aft wall of the turret bay, elevator rail aft mounts",
        "bulkhead", "YK250-CH-005",
        [cut("C-HARN-1330", "harness / coax trunks", [0.120, 0.175], [0.030, 0.068], mirror=True),
         cut("C-TDOOR-SHAFT", "turret-door drive shaft (actuator EQ-TDOORACT on the aft face -> crank and link to the "
             "door rack in the bay; bushed; fix round 2: raised inboard, corners >= inset + 20 mm edge band)",
             [0.126, 0.144], [-0.100, -0.084], mirror=True)],
        name_tr="taret bölmesi arka perdesi")
    add("FS1490", X_PFF, "parachute-bay forward bulkhead: forward wall of the parachute compartment, hatch hinge "
        "land, forward end of the parachute floor", "bulkhead", "YK250-CH-006",
        [cut("C-HARN-1490", "harness / coax trunks (fix round 2, PK2-02: inboard and lower, corners >= inset + 20 "
             "mm edge band)", [0.170, 0.220], [0.020, 0.050], mirror=True)],
        name_tr="paraşüt bölmesi ön perdesi")
    add("FS1810", X_PFR, "parachute-bay aft bulkhead + forward bridle fitting (dorsal) + LERX apex frame (side-of-"
        "body rib and LERX rib 1 forward lands): forward wall of the mission-computer bay, start of the dorsal spine "
        "channel, hatch latch land", "fitting frame", "YK250-CH-007",
        [cut("C-HARN-1810", "harness / coax trunks", [0.170, 0.220], [0.020, 0.050], mirror=True),
         notch("C-BRIDLE-F", "bridle forward leg passage over the frame top (open to the deployment: the leg lifts "
               "out of it)", [-0.015, 0.015], 0.150, "P-PARAHATCH")],
        name_tr="paraşüt bölmesi arka perdesi / ön kayış bağlantısı / LERX burun çerçevesi")
    add("FS-FUEL", X_FUELF, "forward fuel-bay bulkhead (vapour-tight): forward wall of the forward fuel cell, aft "
        "wall of the mission-computer bay, forward end of the keel beams and payload-bay roof deck", "bulkhead",
        "YK250-CH-008",
        [cut("C-HARN-FUEL", "harness trunk (below the fuel cell floor, sealed grommet; fix round 3: lowered with "
             "the trunk, PK3-01/05)", [0.240, 0.300], [-0.120, -0.080], mirror=True),
         notch("C-SPINE-FUEL", "dorsal spine channel M-SPINE (sealed trough, bridle aft leg inside; the leg tears out "
               "upward)", [-0.024, 0.024], 0.159, "P-SPINE")], name_tr="ön yakıt bölmesi perdesi",
        notes="fix round 1 (VPK-13): no wing-harness notch in this vapour-tight bulkhead; the wing branch H-WING "
              "runs below the forward fuel deck and enters the centre wing box through its lower cover")
    add("FS-MS", X_MS0, "main-spar frame: carry-through main spar web inside the body (chevron along the main-spar "
        "line, 8 deg each side, centre kink fitting), forward wall of the saddle fuel bay, rear wall of the forward "
        "fuel bay; below the box only the outboard posts (payload bay open)", "spar frame", "YK250-CH-009",
        [cut("C-PAYLOAD-MS", "payload bay (open, below the box)", [-0.205, 0.205], [-0.215, zb0 - 0.004],
             kind="bay"),
         cut("C-FUEL-MS", "saddle fill / overflow line FL-FILL-S (sealed union)", [-0.040, 0.040], [0.080, 0.110]),
         cut("C-FUEL-MS-LO", "bottom fuel interconnect FL-XFER-LO under the box (sealed union; fix round 3, PK3-01)",
             [0.325, 0.355], [-0.085, -0.055], mirror=True),
         cut("C-VENT-MS", "top vent interconnect FL-VENT-1 (sealed union; fix round 3, PK3-01)", [0.024, 0.048],
             [0.126, 0.150]),
         notch("C-SPINE-MS", "dorsal spine channel M-SPINE (sealed trough; the bridle aft leg tears out upward)",
               [-0.024, 0.024], 0.159, "P-SPINE"),
         cut("C-HARN-MS", "harness trunks H-MAIN / H-COAX / H-WING (sealed grommet; fix round 3: lowered with the "
             "trunks, PK3-01/05)", [0.255, 0.315], [-0.122, -0.078], mirror=True)],
        sweep=SW_MS, notes="the box itself (spar caps and webs) is part YK250-CH-001; this part is the frame above "
        "and below the box (fuel-bay wall and outboard posts) bonded and bolted to the spar web",
        name_tr="ana kiriş çerçevesi")
    add("FS-RS", X_RS0, "rear-spar frame: carry-through rear spar web (chevron, 4.8 deg), rear wall of the saddle "
        "fuel bay, forward wall of the aft fuel bay; aft riser fitting (dorsal); forward ends of the main-gear beams "
        "and of the well roof deck", "spar frame", "YK250-CH-010",
        [cut("C-PAYLOAD-RS", "payload bay (open, below the box)", [-0.205, 0.205], [-0.215, zb0 - 0.004],
             kind="bay"),
         cut("C-FUEL-SAD", "saddle drain line FL-XFER-SA at the saddle floor (sealed union; fix round 3, PK3-01)",
             [-0.020, 0.020], [0.044, 0.072]),
         cut("C-FUEL-RS-LO", "bottom fuel interconnect FL-XFER-LO under the box (sealed union; fix round 3, PK3-01)",
             [0.325, 0.355], [-0.085, -0.055], mirror=True),
         cut("C-VENT-RS", "top vent interconnect FL-VENT-2 (sealed union; fix round 3, PK3-01)", [0.024, 0.048],
             [0.126, 0.150]),
         cut("C-HARN-RS", "harness trunks H-MAIN / H-COAX (sealed grommet; fix round 3: lowered with the trunks, "
             "H-COAX descending to its lower tier, PK3-01/05)", [0.255, 0.315], [-0.142, -0.078], mirror=True)],
        sweep=SW_RS, name_tr="arka kiriş çerçevesi")
    add("FS-GEAR", X_GEARF, "aft main-gear frame + aft fuel-bay bulkhead (vapour-tight): aft ends of the gear beams "
        "and trunnion fittings, inner-door actuator mounts (aft face), forward wall of the aft equipment bay",
        "bulkhead", "YK250-CH-011",
        [cut("C-FUEL-FEED", "engine feed line (sealed union)", [0.020, 0.060], [-0.040, -0.010]),
         cut("C-FUEL-RET", "fuel return line (sealed union)", [0.093, 0.117], [-0.031, -0.003]),
         cut("C-FUEL-VENT", "fuel vent line (sealed union)", [0.063, 0.087], [0.105, 0.135]),
         cut("C-HARN-CL", "centre-line harness conduit (H-MAIN, H-COAX; sealed grommets)", [-0.025, 0.025],
             [-0.115, -0.066]),
         cut("C-DOORLINK", "inner-door and trunnion-door drive pushrods (DA 22 crank -> door hinge horns; fix round "
             "2: raised, corners >= inset + 20 mm edge band)", [0.010, 0.045], [-0.160, -0.142], mirror=True)],
        name_tr="arka ana takım çerçevesi / arka yakıt perdesi")
    add("FS3480", 3.480, "tail ring frame: fin front-spar fittings, stabilator-stub front-spar fittings, cooling "
        "inlet duct pass-through, aft end of the equipment bay; open centre for the equipment bay and the S-duct",
        "ring", "YK250-CH-012", [], ring_depth=0.040, name_tr="kuyruk halka çerçevesi")
    add("FS3670", X_FW, "firewall: fireproof bulkhead (CS-VLA 1191): firewall corner fittings (engine-mount upper "
        "feet, fin rear spars, dorsal-longeron splices), lower engine-mount feet, stabilator node fittings (chine "
        "splices) on the aft face, ventral front fitting, stabilator actuators on the forward face, fuel shut-off "
        "valve forward of it; no carbon member crosses it (fix round 1, VPK-06)", "firewall", "YK250-CH-013",
        [cut("C-DUCT", "cooling-air duct exit (stainless spigot ring + fireproof seal; fix round 2, PK2-02: the duct "
             "exit flattened to 180 x 73 mm so that the firewall keeps a continuous rim >= inset + 20 mm edge band "
             "above it, keep-out KO-COOLING-DUCT exit_section)", [-0.090, 0.090], [0.238, 0.311]),
         cut("C-FW-FUEL", "fuel feed/return (fireproof bulkhead unions + fire sleeve)", [0.030, 0.060],
             [0.020, 0.050]),
         cut("C-FW-HARN", "engine harness / SG750 power (fireproof grommets; fix round 2: lowered below the "
             "lower engine-mount feet so that the 82 mm solid land around each foot keeps an uninterrupted core-shear "
             "perimeter, structures FW-FOOT-CORE; corners >= inset + 20 mm edge band)", [0.080, 0.110],
             [-0.035, 0.000], mirror=True),
         cut("C-FW-PUSHROD", "stabilator pushrods (fireproof bellows boots)", [0.165, 0.195], [0.215, 0.262],
             mirror=True)],
        mat={"material": "cfrp_pw_mtm45_as4", "process": "prepreg_ooa_vacbag", "layup": "rib_panel", "t": 0.0148,
             "construction": "stack-up forward -> aft: CFRP sandwich bulkhead (layups.rib_panel, 6.8 mm) / 7.6 mm "
                             "air gap on 12 stainless stand-offs (insulation blanket optional, material to be "
                             "selected) / 0.4 mm AISI 304 stainless sheet (fireproof without test: >= 0.38 mm, "
                             "standards.yaml FIRE-001, CS-VLA 1191), riveted to a stainless edge angle; overall "
                             "14.8 mm", "shield_material": "ss_304_annealed", "shield_t": 0.0004},
        name_tr="yangın perdesi")
    add("FS3738", X_RING, "engine-bay lower U-ring (metallic, in the hot zone): ventral rear fitting, aft keel beam, "
        "lower cowl intermediate land; its upper ends are riveted to the feet of the outboard cheeks of the stabilator "
        "node fittings; open centre for the engine (dynamic envelope + 10 mm); fix round 1 (VPK-01): the ring no "
        "longer carries the spindle bearings (the 30 mm band at the spindle could not hold a 25 mm spindle hole and "
        "the housing bolts) and ends below the node fittings (ring_z_max)", "ring", "YK250-CH-014", [],
        ring_depth=0.030, ring_z_max=0.176, flange_w=0.020,
        mat={"material": "al_2024_t3_sheet", "process": "sheet_metal_aluminium", "layup": None, "t": 0.002,
             "construction": "2024-T3 sheet web 2.0 mm, formed flanges 20 mm (bend radius >= 6 t = 12 mm per "
                             "processes.sheet_metal_aluminium: the flat part of each flange is 6 mm, so the lower "
                             "cowl Camloc receptacles are on separate 7075 land clips riveted to the web); no "
                             "composite inside the engine-bay hot-zone keep-out; fix round 2 (VS2-03): the bottom of "
                             "the U between y -0.15 and +0.15 is a machined 7075-T651 lower segment (I 60 x 20 x 1.6 / "
                             "2.0 mm, structures.sizing.body.fs3738_lower_segment; 150-180 mm free height to the engine "
                             "envelope + 10 mm there) carrying the tail-bumper keel reaction; the aft keel beam is "
                             "bolted to its web (4 x M5), the 2024 legs are spliced to its ends (3 x M5 each)",
             "lower_segment": {"y": [-0.150, 0.150], "depth_m": 0.060, "material": "al_7075_t651_plate",
                               "process": "cnc_milling_metal", "part": "YK250-CH-015"}},
        notes="x = stabilator pivot station (tail.surfaces.stabilator.pivot); U-ring below z 0.176",
        name_tr="motor bölmesi alt U halkası")
    chine_notches(st)
    return st


CHINE_W, CHINE_H = 0.035, 0.030          # M-CHINE J-section (b_chassis.members)


def chine_ranges() -> list:
    """x ranges of the two chine-longeron pieces (b_chassis.members M-CHINE paths)."""
    return [(0.6034, spar_x(0.38, 0.25) - 0.030), (spar_x(0.38, 0.72) + 0.030, X_FW_FWD - 0.0010)]


def chine_notches(st: list) -> None:
    """Fix round 3 (PK3-04): every frame whose web the chine longeron M-CHINE crosses gets a longeron notch open to
    the frame edge: the J-section (35 x 30 mm) + 1 mm all round, so that the longeron is placed laterally (from
    outboard) into the notches of the frames already in the jig; a 7075 shear clip ties the frame web to the longeron
    web and a bonded U-doubler carries the frame edge band round the notch (layout_check C02)."""
    for s_ in st:
        x = float(s_["x"])
        t = float(s_.get("t", 0.0068))
        if s_.get("sweep_deg") or not any(a + 0.5 * t < x < b - 0.5 * t for a, b in chine_ranges()):
            continue
        yc, zz = chine_halfwidth(x) - 0.020, zc(x)
        s_["cutouts"].append({
            "id": "C-CHINE", "purpose": "chine longeron M-CHINE (J 35 x 30 mm) crossing the frame web",
            "kind": "longeron notch", "member": "M-CHINE", "mirror": True,
            "y": r3([yc - 0.5 * CHINE_W - 0.001, chine_halfwidth(x) + 0.010]),
            "z": r3([zz - 0.5 * CHINE_H - 0.001, zz + 0.5 * CHINE_H + 0.001]),
            "insertion": "lateral, from outboard (the notch is open to the frame edge): the longeron piece is placed "
                         "after the frames are pinned in the jig",
            "clip": "7075-T651 shear clip (angle 20 x 20 x 1.6 mm, 40 mm long): 2 x M4 Ti to the frame web land, "
                    "2 x M4 Ti to the longeron web",
            "doubler": "bonded U-doubler PW 16 plies (3.2 mm) x 20 mm round the notch, ends 25 mm past the notch "
                       "corners into the edge band"})
