#!/usr/bin/env python3
"""YK-250 (ucav250) research phase: airfoil polars (NeuralFoil) and propeller operating-point estimates.

What it does
1. ``--download``: fetches the candidate coordinate files from the UIUC Airfoil Coordinates Database
   (https://m-selig.ae.illinois.edu/ads/coord/), cleans them and writes them in Selig format
   (TE -> upper -> LE -> lower -> TE, first line = original title) to ``ucav250/data/airfoils/<file>.dat``.
   Ordinates are NOT rescaled or smoothed; only the point order (Lednicer -> Selig), junk lines
   ("......", "(0.0016)", Lednicer point counts, the trailing "100.00" line of naca23015.dat) and duplicate
   LE points are fixed.  NACA 4412/4418 (added candidates) are NOT written as files: the UIUC copies have only
   17 points per side and a file named naca44xx.dat would shadow the exact analytic NACA generator in
   ucav250/design/oml.py; they are analysed from analytic ordinates (aerosandbox).
2. Geometry (PCHIP on each surface): t/c and its x/c, camber, thickness at spar stations, section and spar-box
   area (fuel volume), TE thickness, upper ordinate at x/c = 0.0125 (Gault 1957 stall-type parameter).
3. Polars: NeuralFoil (model_size 'large') on the aerosandbox Kulfan (CST) fit of the coordinates, alpha -4..16
   deg in 0.25 deg steps (extended to 22 deg only to locate cl_max), Re 0.8e6 / 1.5e6 / 2.5e6 (tails also 0.5e6):
      ncrit9   n_crit 9, free transition         clean production surface, low-turbulence air
      ncrit5   n_crit 5, free transition         task-defined rough/contaminated case (physically: earlier
                                                  free transition, i.e. higher turbulence / mild roughness)
      tripped  n_crit 9, xtr 0.075 both surfaces  fully turbulent proxy for insects/rain/erosion; same trip
                                                  station as NASA TP-1861 and close to NACA 'standard
                                                  roughness' (0.08c, NACA Rep. 824)
   Cross-checks: 'xlarge' model at Re 1.5e6/ncrit9; UIUC vs analytic ordinates for NACA 4415 and 0010.
4. Propellers: manufacturer performance tables of Mejzlik carbon propellers (thrust/torque/power versus rpm at
   0-50 m/s; Mejzlik 'Propulsion system data' sheets, ISA sea level, measured engine data + Mejzlik propeller
   simulation) are matched to the Limbach L 275 EF WOT torque curve (engine.yaml) to estimate static thrust,
   WOT rpm in flight, and the fixed-pitch partial-throttle efficiency at the cruise thrust required at
   30/35/40 m/s.  All derived operating points are estimates.

Usage (from the repo root)
    python3 ucav250/data/research/aero_polars.py --download          # refresh the .dat files
    python3 ucav250/data/research/aero_polars.py                     # print the generated YAML block
    python3 ucav250/data/research/aero_polars.py --update-yaml       # replace the generated block in aero.yaml

The generated block in aero.yaml sits between the lines
    # >>> BEGIN GENERATED BY aero_polars.py
    # <<< END GENERATED BY aero_polars.py
Everything outside the markers is hand-written research and is never touched by this script.

Environment: numpy 1.26.4, neuralfoil 0.3.3, aerosandbox 4.2.8, scipy, pyyaml (see ucav250/setup_env.sh).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import math
import re
import sys
import urllib.request
from pathlib import Path

import numpy as np
from scipy.interpolate import PchipInterpolator

HERE = Path(__file__).resolve().parent
PKG = HERE.parents[1]                                   # ucav250/
AIRFOIL_DIR = PKG / "data" / "airfoils"
AERO_YAML = HERE / "aero.yaml"
UIUC_URL = "https://m-selig.ae.illinois.edu/ads/coord/"
BEGIN = "# >>> BEGIN GENERATED BY aero_polars.py"
END = "# <<< END GENERATED BY aero_polars.py"

# ---------------------------------------------------------------------------------------------------------------------
# candidates: (file or analytic name, display name, coordinate source, why included)
# ---------------------------------------------------------------------------------------------------------------------
WING = [
    ("naca4415", "NACA 4415", "uiuc", "task candidate"),
    ("n63415", "NACA 63(2)-415", "uiuc", "task candidate"),
    ("naca23015", "NACA 23015", "uiuc", "task candidate"),
    ("nlf416", "NASA NLF(1)-0416", "uiuc", "task candidate"),
    ("fx63137", "Wortmann FX 63-137", "uiuc", "task candidate"),
    ("e1210", "Eppler E1210", "uiuc", "task candidate"),
    ("sd7062", "Selig-Donovan SD7062", "uiuc", "task reference (YK-38 wing section)"),
    ("naca4412", "NACA 4412", "analytic", "added: thinner tip partner of NACA 4415"),
    ("naca4418", "NACA 4418", "analytic", "added: thicker root partner of NACA 4415"),
    ("ls417", "NASA LS(1)-0417 (GA(W)-1)", "uiuc", "added: thick high-lift GA section"),
    ("naca642415", "NACA 64(2)-415", "uiuc", "added: classic 6-series laminar 15 %"),
    ("nlf0115", "NASA NLF(1)-0115", "uiuc", "added: low-cm NLF GA section, possible tip partner of NLF(1)-0416"),
    ("nlf1015", "NASA NLF(1)-1015", "uiuc", "added: NLF section designed for a high-altitude long-endurance UAV"),
]
TAIL = [
    ("n0009sm", "NACA 0009 (smoothed)", "uiuc", "task candidate (UIUC has only the smoothed 0009)"),
    ("naca0010", "NACA 0010", "uiuc", "task candidate"),
    ("n0012", "NACA 0012", "uiuc", "task candidate"),
    ("n63012a", "NACA 63-012A", "uiuc", "task candidate 63-012 (UIUC has only the 63-012A ordinates)"),
]
SOURCE_CHECK = [("naca4415", "naca4415"), ("naca0010", "naca0010")]   # UIUC file vs analytic NACA equations

RE_WING = (0.8e6, 1.5e6, 2.5e6)
RE_TAIL = (0.5e6, 0.8e6, 1.5e6, 2.5e6)
ALPHA = np.round(np.arange(-4.0, 22.0 + 1e-9, 0.25), 4)   # task sweep is -4..16 deg; 16..22 only to find the stall
ALPHA_TASK_MAX = 16.0
CASES = {
    "ncrit9": dict(n_crit=9.0, xtr_upper=1.0, xtr_lower=1.0),
    "ncrit5": dict(n_crit=5.0, xtr_upper=1.0, xtr_lower=1.0),
    "tripped": dict(n_crit=9.0, xtr_upper=0.075, xtr_lower=0.075),
}
MODEL = "large"
NF_URL = "https://github.com/peterdsharpe/NeuralFoil"
CL_CRUISE = 0.6        # section cl at ~36 m/s, W/S 490 Pa, sea level (aero.yaml design_point)
CL_LOITER = 0.9        # section cl at best endurance ~30 m/s, sea level
BUCKET_FACTOR = 1.10   # drag bucket = contiguous cl range with cd <= 1.10 * cd_min


# =====================================================================================================================
# coordinates
# =====================================================================================================================
def _num(tok: str) -> float | None:
    tok = tok.strip().strip("()")
    try:
        return float(tok)
    except ValueError:
        return None


def parse_uiuc(text: str) -> tuple[str, np.ndarray]:
    """Parse a UIUC .dat (Selig or Lednicer, with junk lines) into (title, Selig-ordered points)."""
    lines = text.splitlines()
    title = lines[0].strip()
    pts = []
    for line in lines[1:]:
        tok = line.replace(",", " ").split()
        if len(tok) < 2:
            continue
        x, y = _num(tok[0]), _num(tok[1])
        if x is None or y is None:
            continue                                    # e.g. "0.0000 ......"
        if abs(x) > 1.05 or abs(y) > 0.5:
            continue                                    # Lednicer point-count header, "100.00 0.0000" junk
        pts.append((x, y))
    P = np.array(pts, float)
    if P[0, 0] < 0.5:                                   # Lednicer: upper LE->TE, then lower LE->TE
        i = int(np.where(np.diff(P[:, 0]) < -0.5)[0][0]) + 1
        up, lo = P[:i], P[i:]
        if np.allclose(lo[0], up[0]):
            lo = lo[1:]
        P = np.vstack([up[::-1], lo])
    keep = np.r_[True, np.any(np.abs(np.diff(P, axis=0)) > 1e-9, axis=1)]
    P = P[keep]
    area = 0.5 * np.sum(P[:-1, 0] * P[1:, 1] - P[1:, 0] * P[:-1, 1])
    if area < 0:                                        # Selig order is counter-clockwise (upper surface first)
        P = P[::-1]
    return title, P


def download(files) -> None:
    AIRFOIL_DIR.mkdir(parents=True, exist_ok=True)
    for f in files:
        url = f"{UIUC_URL}{f}.dat"
        with urllib.request.urlopen(url, timeout=60) as r:
            text = r.read().decode("latin-1")
        title, P = parse_uiuc(text)
        body = "\n".join(f" {x:10.7f} {y:10.7f}" for x, y in P)
        (AIRFOIL_DIR / f"{f}.dat").write_text(f"{title}\n{body}\n")
        print(f"downloaded {url} -> {AIRFOIL_DIR / (f + '.dat')} ({len(P)} points)", file=sys.stderr)


def load(file: str, source: str = "uiuc") -> tuple[str, np.ndarray]:
    if source == "analytic":
        import aerosandbox as asb
        af = asb.Airfoil(file).repanel(n_points_per_side=120)
        return f"{file.upper()} (analytic NACA equations, aerosandbox)", np.asarray(af.coordinates, float)
    lines = (AIRFOIL_DIR / f"{file}.dat").read_text().splitlines()
    P = np.array([[float(v) for v in ln.split()[:2]] for ln in lines[1:] if ln.strip()])
    return lines[0].strip(), P


# =====================================================================================================================
# geometry
# =====================================================================================================================
def _surfaces(P):
    ile = int(np.argmin(P[:, 0]))
    up, lo = P[: ile + 1][::-1], P[ile:]
    out = []
    for s in (up, lo):
        s = s[np.argsort(s[:, 0], kind="stable")]
        s = s[np.r_[True, np.diff(s[:, 0]) > 1e-9]]
        out.append(PchipInterpolator(s[:, 0], s[:, 1]))
    return out


def geometry(P: np.ndarray) -> dict:
    """Section geometry on unit chord (LE = min x, chord = max x - min x)."""
    x0, c = P[:, 0].min(), P[:, 0].max() - P[:, 0].min()
    fu, fl = _surfaces((P - [x0, 0.0]) / c)
    xs = 0.5 * (1 - np.cos(np.linspace(0, math.pi, 2001)))
    yu, yl = fu(xs), fl(xs)
    t, cam = yu - yl, 0.5 * (yu + yl)
    it, ic = int(np.argmax(t)), int(np.argmax(np.abs(cam)))

    def box(a, b):
        m = (xs >= a) & (xs <= b)
        return float(np.trapz(t[m], xs[m]))

    def t_at(xc):
        return round(float(fu(xc) - fl(xc)), 4)

    return {
        "t_over_c": round(float(t[it]), 4),
        "x_t_max_over_c": round(float(xs[it]), 3),
        "camber_over_c": round(float(cam[ic]), 4),
        "x_camber_max_over_c": round(float(xs[ic]), 3),
        "t_at_x0p25_over_c": t_at(0.25),
        "t_at_x0p30_over_c": t_at(0.30),
        "t_at_x0p65_over_c": t_at(0.65),
        "t_at_x0p90_over_c": t_at(0.90),
        "te_thickness_over_c": round(float(yu[-1] - yl[-1]), 4),
        "area_over_c2": round(float(np.trapz(t, xs)), 4),
        "box_area_x0p20_x0p65_over_c2": round(box(0.20, 0.65), 4),
        "y_upper_at_x0p0125_percent_c": round(100 * float(fu(0.0125) - 0.0), 2),
        "n_points": int(len(P)),
    }


def gault_stall_type(y125_pct: float) -> str:
    """Stall type from Gault (NACA TN 3963, Fig. 1) for Re ~1-3e6; region boundaries read from the figure
    (+/- 0.2 % c).  The correlation is for smooth models in low turbulence."""
    if y125_pct >= 2.2:
        return "trailing-edge"
    if y125_pct >= 1.75:
        return "combined leading-/trailing-edge (transitional)"
    if y125_pct >= 1.2:
        return "leading-edge"
    return "thin-airfoil"


# =====================================================================================================================
# polars
# =====================================================================================================================
def kulfan(name: str, P: np.ndarray):
    import aerosandbox as asb
    af = asb.Airfoil(name=name, coordinates=P)
    kaf = af.to_kulfan_airfoil()
    fu0, fl0 = _surfaces(np.asarray(af.coordinates))
    fu1, fl1 = _surfaces(np.asarray(kaf.to_airfoil().coordinates))
    xs = np.linspace(0.005, 0.995, 199)
    err = max(np.max(np.abs(fu0(xs) - fu1(xs))), np.max(np.abs(fl0(xs) - fl1(xs))))
    return kaf, float(err)


def polar(kaf, Re: float, case: str, model: str = MODEL) -> dict:
    import neuralfoil as nf
    r = nf.get_aero_from_kulfan_parameters(kaf.kulfan_parameters, alpha=ALPHA, Re=Re, model_size=model, **CASES[case])
    return {k: np.asarray(r[k], float) for k in ("CL", "CD", "CM", "Top_Xtr", "Bot_Xtr", "analysis_confidence")}


def _r(v, n=4):
    return None if v is None or not np.isfinite(v) else round(float(v), n)


def metrics(p: dict) -> dict:
    a, cl, cd, cm = ALPHA, p["CL"], p["CD"], p["CM"]
    i_max = int(np.argmax(cl))
    task = a <= ALPHA_TASK_MAX
    i_task = int(np.argmax(np.where(task, cl, -9.0)))
    i_min = int(np.argmin(np.where(task, cd, 9.0)))
    lim = BUCKET_FACTOR * cd[i_min]
    lo = i_min
    while lo > 0 and cd[lo - 1] <= lim:
        lo -= 1
    hi = i_min
    while hi < len(a) - 1 and cd[hi + 1] <= lim and a[hi + 1] <= ALPHA_TASK_MAX:
        hi += 1
    br = slice(0, i_max + 1)                        # pre-stall branch for cl-based interpolation
    clb = cl[br]
    order = np.argsort(clb)

    def at_cl(arr, c):
        if c < clb.min() or c > clb.max():
            return None
        return float(np.interp(c, clb[order], arr[br][order]))

    ld = np.where(task, cl / cd, -1e9)
    i_ld = int(np.argmax(ld))
    e = np.where(task & (cl > 0), np.abs(cl) ** 1.5 / cd, 0.0)
    i_e = int(np.argmax(e))
    lin = (a >= -2.0) & (a <= 4.0)
    slope, icpt = np.polyfit(a[lin], cl[lin], 1)
    cd06, cd09 = at_cl(cd, CL_CRUISE), at_cl(cd, CL_LOITER)
    post = None
    if a[i_max] + 3.0 <= a[-1]:
        post = float(np.interp(a[i_max] + 3.0, a, cl)) / float(cl[i_max])
    return {
        "cl_max": _r(cl[i_max], 3),
        "alpha_cl_max_deg": _r(a[i_max], 2),
        "cl_max_beyond_22deg": bool(i_max >= len(a) - 1),
        "cl_max_within_alpha_m4_16deg": _r(cl[i_task], 3),
        "cd_min": _r(cd[i_min], 5),
        "cl_at_cd_min": _r(cl[i_min], 3),
        "drag_bucket_cl_range": [_r(cl[lo], 3), _r(cl[hi], 3)],
        "cl_alpha_per_deg": _r(slope, 4),
        "alpha_zero_lift_deg": _r(-icpt / slope, 2),
        "cm_c4_at_cl_cruise": _r(at_cl(cm, CL_CRUISE), 4),
        "cm_c4_at_cl_loiter": _r(at_cl(cm, CL_LOITER), 4),
        "cd_at_cl_cruise": _r(cd06, 5),
        "cd_at_cl_loiter": _r(cd09, 5),
        "cd_at_cl_1p1": _r(at_cl(cd, 1.1), 5),
        "cd_at_cl_1p3": _r(at_cl(cd, 1.3), 5),
        "l_over_d_at_cl_cruise": _r(CL_CRUISE / cd06, 1) if cd06 else None,
        "l_over_d_at_cl_loiter": _r(CL_LOITER / cd09, 1) if cd09 else None,
        "l_over_d_max": _r(ld[i_ld], 1),
        "cl_at_l_over_d_max": _r(cl[i_ld], 3),
        "endurance_cl15_over_cd_max": _r(e[i_e], 1),
        "cl_at_endurance_max": _r(cl[i_e], 3),
        "xtr_upper_at_cl_cruise": _r(at_cl(p["Top_Xtr"], CL_CRUISE), 3),
        "xtr_lower_at_cl_cruise": _r(at_cl(p["Bot_Xtr"], CL_CRUISE), 3),
        "post_stall_cl_ratio_at_alpha_clmax_plus3deg": _r(post, 3),
        "analysis_confidence_min_prestall": _r(p["analysis_confidence"][br].min(), 3),
    }


def _rekey(Re):
    return f"Re_{Re / 1e6:g}e6"


def run_airfoils() -> dict:
    out = {}
    for group, items, res in (("wing", WING, RE_WING), ("tail", TAIL, RE_TAIL)):
        for file, name, src, why in items:
            title, P = load(file, src)
            g = geometry(P)
            kaf, fit_err = kulfan(name, P)
            entry = {"name": name, "group": group, "tag": "estimate", "source": NF_URL, "coordinate_source": src,
                     "file": f"ucav250/data/airfoils/{file}.dat" if src == "uiuc" else None,
                     "uiuc_url": f"{UIUC_URL}{file}.dat", "title": title, "why_included": why,
                     "geometry": g, "gault_stall_type_Re_1_3e6": gault_stall_type(g["y_upper_at_x0p0125_percent_c"]),
                     "kulfan_fit_max_dy_over_c": round(fit_err, 5), "polars": {}}
            for case in CASES:
                entry["polars"][case] = {_rekey(Re): metrics(polar(kaf, Re, case)) for Re in res}
            mx = metrics(polar(kaf, 1.5e6, "ncrit9", "xlarge"))
            ml = entry["polars"]["ncrit9"]["Re_1.5e6"]
            entry["model_size_check_Re_1.5e6_ncrit9"] = {
                k: {"large": ml[k], "xlarge": mx[k]} for k in ("cl_max", "cd_min", "cm_c4_at_cl_cruise", "l_over_d_max")}
            out[file] = entry
            print(f"polars done: {file}", file=sys.stderr)
    return out


def source_check() -> dict:
    """UIUC ordinates vs exact NACA equations (aerosandbox), Re 1.5e6, ncrit 9."""
    res = {}
    for file, naca in SOURCE_CHECK:
        rows = {}
        for lab, (f, s) in (("uiuc_file", (file, "uiuc")), ("analytic", (naca, "analytic"))):
            _, P = load(f, s)
            kaf, _ = kulfan(lab, P)
            m = metrics(polar(kaf, 1.5e6, "ncrit9"))
            g = geometry(P)
            rows[lab] = {"y_upper_at_x0p0125_percent_c": g["y_upper_at_x0p0125_percent_c"], "t_over_c": g["t_over_c"],
                         **{k: m[k] for k in ("cl_max", "alpha_cl_max_deg", "cd_min", "cm_c4_at_cl_cruise",
                                              "l_over_d_max")}}
        res[file] = rows
    return {"tag": "estimate", "source": NF_URL, **res}


def summary_table(af: dict, rekey: str = "Re_1.5e6") -> list:
    """One flow-style row per airfoil at one Reynolds number (1.5e6: sea-level cruise; 0.8e6: loiter at altitude)."""
    rows = []
    for file, e in af.items():
        c9, c5, tr = (e["polars"][c][rekey] for c in ("ncrit9", "ncrit5", "tripped"))
        g = e["geometry"]

        def ratio(a, b):
            return None if (a is None or b is None) else round(a / b, 2)
        rows.append({
            "airfoil": file, "group": e["group"], "t_over_c": g["t_over_c"], "x_t": g["x_t_max_over_c"],
            "cl_max_n9": c9["cl_max"], "alpha_clmax_n9": c9["alpha_cl_max_deg"], "cl_max_n5": c5["cl_max"],
            "cl_max_trip": tr["cl_max"], "cd_min_n9": c9["cd_min"], "cl_cdmin_n9": c9["cl_at_cd_min"],
            "bucket_n9": c9["drag_bucket_cl_range"], "cm_cruise_n9": c9["cm_c4_at_cl_cruise"],
            "cd_cruise_n9": c9["cd_at_cl_cruise"], "cd_cruise_n5": c5["cd_at_cl_cruise"],
            "cd_cruise_trip": tr["cd_at_cl_cruise"],
            "cd_ratio_trip_n9_cruise": ratio(tr["cd_at_cl_cruise"], c9["cd_at_cl_cruise"]),
            "cd_1p1_n9": c9["cd_at_cl_1p1"], "cd_1p1_trip": tr["cd_at_cl_1p1"],
            "ld_max_n9": c9["l_over_d_max"], "ld_max_trip": tr["l_over_d_max"],
            "endurance_n9": c9["endurance_cl15_over_cd_max"], "endurance_trip": tr["endurance_cl15_over_cd_max"],
            "post_stall_ratio_n9": c9["post_stall_cl_ratio_at_alpha_clmax_plus3deg"],
            "stall_type_gault": e["gault_stall_type_Re_1_3e6"],
        })
    return rows


# =====================================================================================================================
# propellers: Mejzlik manufacturer tables matched to the L 275 EF
# =====================================================================================================================
RHO_SL, A_SL, G0 = 1.225, 340.29, 9.80665          # ISA sea level
# L 275 EF WOT curve read from the Limbach datasheet (engine.yaml -> limbach_l275_ef.wot_curve_read_from_datasheet)
ENG_RPM = np.array([4000, 4500, 5000, 5500, 6000, 6500, 7000, 7500], float)
ENG_Q = np.array([25.3, 25.4, 25.9, 25.6, 25.7, 24.7, 24.0, 23.7], float)        # N m
ENG_RPM_MAX_CONT, ENG_RPM_MAX = 6000.0, 7500.0       # 'regular flight 4000-6000 rpm'; 18 kW at 7500 rpm
# cruise thrust required (estimate): D = q S CD0 + W^2 / (q S pi e AR); comparables.yaml recommended_ranges nominals
DRAG = dict(mass_kg=150.0, S_m2=3.0, AR=12.0, CD0=0.035, e=0.75)
CD0_BAND = (0.030, 0.040)
MZ = "https://www.mejzlik.eu/files/"
# Mejzlik sheets: rows (rpm, thrust N, torque N m, shaft power W) at flight speed V [m/s] (keys).  Rows < 2500 rpm
# dropped.  Sheets 0096 (32x12 2B) and 0099 (31x12 EVO LF) are excluded: their static and 40 m/s tables are
# identical to each other (copy error) and 0096 shows physically implausible 30 m/s thrust.
MEJZLIK = [
    dict(id='0100', label='26x12 2B', D_in=26, P_in=12, blades=2, mass_kg=0.197, ref_engine='Hirth 4103',
         url=MZ + '0100-hirth-motor-4103-mejzlik-26x12-2b-rev01.pdf',
         t={
            0: [(3100,51,1.91,619), (3900,83,3.04,1243), (4600,116,4.32,2083), (5300,159,5.89,3268), (5400,166,6.17,3491), (6000,208,7.78,4886), (6800,274,10.52,7493)],
            20: [(3100,13,1.24,401), (3900,39,2.7,1103), (4600,70,4.23,2038), (5300,108,6.06,3362), (5400,114,6.34,3585), (6000,153,8.18,5139), (6800,214,11.03,7855)],
            30: [(3100,-10,0.3,97), (3900,3,1.09,443), (4600,29,2.71,1305), (5300,62,4.64,2574), (5400,67,4.94,2794), (6000,103,6.88,4322), (6800,160,9.85,7018)],
            40: [(3100,-22,-0.21,-69), (3900,-20,0.37,150), (4600,-12,0.7,335), (5300,11,2.17,1207), (5400,15,2.48,1402), (6000,46,4.5,2827), (6800,97,7.61,5419)],
            50: [(3100,-25,-0.84,-273), (3900,-34,-0.28,-114), (4600,-34,0.3,146), (5300,-27,0.73,406), (5400,-26,0.81,457), (6000,-12,1.51,949), (6800,28,4.26,3033)],
         }),
    dict(id='0124', label='26x14 2B TH', D_in=26, P_in=14, blades=2, mass_kg=0.183, ref_engine='Hirth 4103',
         url=MZ + '0124-hirth-motor-4103-mejzlik-26x14-2b-th-rev01.pdf',
         t={
            0: [(3100,55,2.03,659), (3900,89,3.29,1345), (4600,126,4.68,2253), (5300,170,6.39,3547), (5400,178,6.59,3727), (6000,221,8.38,5262), (6800,292,11.09,7894)],
            20: [(3100,18,1.45,472), (3900,47,3.1,1265), (4600,80,4.76,2293), (5300,119,6.62,3672), (5400,125,6.9,3903), (6000,165,8.77,5508), (6800,229,11.74,8357)],
            30: [(3100,-14,-0.2,-65), (3900,10,1.37,558), (4600,40,3.23,1555), (5300,77,5.36,2975), (5400,83,5.68,3215), (6000,121,7.75,4868), (6800,181,10.9,7759)],
            40: [(3100,-25,-0.52,-168), (3900,-26,-0.51,-207), (4600,-6,0.78,374), (5300,26,2.79,1546), (5400,31,3.11,1760), (6000,66,5.32,3342), (6800,122,8.78,6249)],
            50: [(3100,-30,-1.1,-357), (3900,-40,-0.85,-347), (4600,-44,-0.95,-457), (5300,-28,0,-1), (5400,-24,0.24,134), (6000,5,2,1254), (6800,55,5.25,3742)],
         }),
    dict(id='0126', label='26.5x16.2 2B', D_in=26.5, P_in=16.2, blades=2, mass_kg=0.192, ref_engine='Zanzottera 101HS',
         url=MZ + '0126-zanzottera-motor-101hs-mejzlik-265x162-2b-rev02.pdf',
         t={
            0: [(3100,65,2.68,870), (3800,100,4.06,1617), (4500,143,5.86,2761), (5200,196,8.08,4399), (5300,204,8.39,4657), (5900,258,10.7,6613), (6700,344,14.41,10112)],
            20: [(3100,33,2.61,849), (3800,66,4.53,1803), (4500,105,6.66,3140), (5200,153,9.17,4992), (5300,161,9.56,5308), (5900,211,12.14,7502), (6700,292,16.24,11391)],
            30: [(3100,1,0.57,186), (3800,31,2.91,1158), (4500,70,5.52,2603), (5200,117,8.45,4600), (5300,124,8.89,4933), (5900,172,11.68,7219), (6700,248,15.98,11214)],
            40: [(3100,-22,-0.56,-182), (3800,-9,-0.02,-8), (4500,24,2.74,1293), (5200,68,6.04,3292), (5300,74,6.54,3632), (5900,121,9.72,6007), (6700,195,14.55,10209)],
            50: [(3100,-31,-1.18,-383), (3800,-33,-0.83,-332), (4500,-22,-0.77,-363), (5200,13,2.08,1131), (5300,19,2.62,1455), (5900,61,6.09,3764), (6700,130,11.28,7913)],
         }),
    dict(id='0127', label='28x10 2B EVO', D_in=28, P_in=10, blades=2, mass_kg=0.230, ref_engine='Zanzottera 101HS',
         url=MZ + '0127-zanzottera-motor-101hs-mejzlik-28x10-2b-evo-rev02.pdf',
         t={
            0: [(2900,57,2.06,624), (3600,89,3.19,1202), (4300,129,4.53,2042), (4900,168,6.1,3131), (5000,176,6.35,3327), (5600,225,8.13,4766), (6300,288,10.64,7020)],
            20: [(2900,2,0.7,212), (3400,19,1.62,577), (4000,44,2.93,1228), (4600,74,4.48,2158), (5000,98,5.63,2949), (5100,105,5.94,3172), (5700,147,7.93,4732), (6300,197,10.21,6737)],
            30: [(2700,-25,-0.33,-92), (3100,-25,-0.2,-66), (3600,-17,0.27,101), (4000,-6,0.81,341), (4500,13,1.9,893), (4900,33,3.02,1550), (5000,38,3.31,1734), (5400,62,4.6,2603), (5800,89,6.07,3685), (6300,127,8.09,5338)],
            40: [(3600,-46,-0.71,-267), (3900,-47,-0.56,-228), (4300,-42,-0.27,-122), (4600,-36,0.04,17), (4900,-26,0.47,240), (5000,-23,0.65,340), (5300,-12,1.2,665), (5600,2,1.95,1145), (5900,19,2.99,1846), (6300,45,4.53,2988)],
         }),
    dict(id='0097', label='28x12 2B', D_in=28, P_in=12, blades=2, mass_kg=0.230, ref_engine='Hirth 4202HF',
         url=MZ + '0097-hirth-motor-4202f-mejzlik-28x12-rev01.pdf',
         t={
            0: [(2500,44,1.7,445), (2750,54,2.06,593), (3000,64,2.48,779), (3250,76,2.94,1000), (3500,89,3.37,1237), (3750,102,3.93,1542), (4000,118,4.51,1890), (4250,134,5.19,2310), (4500,152,5.82,2744), (4750,169,6.58,3271), (5000,189,7.3,3822), (5250,209,8.11,4456), (5500,230,9.04,5206), (5750,255,9.93,5981), (6000,281,10.89,6844), (6250,308,12.14,7947), (6500,336,13.32,9068)],
            20: [(2500,1,0.45,117), (2750,9,0.98,282), (3000,17,1.54,484), (3250,27,2.14,728), (3500,37,2.76,1012), (3750,49,3.42,1345), (4000,62,4.13,1729), (4250,76,4.87,2169), (4500,91,5.65,2664), (4750,107,6.48,3225), (5000,125,7.36,3853), (5250,144,8.28,4553), (5500,164,9.26,5336), (5750,186,10.3,6204), (6000,208,11.42,7174), (6250,233,12.62,8258), (6500,259,13.9,9464)],
            30: [(2500,-20,-0.66,-173), (2750,-20,-0.74,-214), (3000,-17,-0.6,-189), (3250,-12,-0.22,-76), (3500,-4,0.4,145), (3750,6,1.13,443), (4000,17,1.93,809), (4250,29,2.78,1237), (4500,42,3.66,1726), (4750,57,4.57,2275), (5000,73,5.54,2899), (5250,90,6.55,3599), (5500,108,7.59,4372), (5750,128,8.7,5240), (6000,149,9.89,6212), (6250,172,11.15,7297), (6500,196,12.48,8492)],
            40: [(2500,-24,-1.1,-288), (2750,-29,-1.25,-361), (3000,-33,-1.37,-430), (3250,-36,-1.52,-518), (3500,-38,-1.67,-612), (3750,-37,-1.84,-724), (4000,-32,-1.5,-628), (4250,-24,-0.91,-404), (4500,-13,-0.02,-9), (4750,-1,0.98,488), (5000,12,2.04,1070), (5250,27,3.15,1733), (5500,43,4.31,2483), (5750,61,5.52,3324), (6000,80,6.78,4262), (6250,101,8.11,5311), (6500,123,9.53,6486)],
            50: [(2500,-29,-2.27,-594), (2750,-33,-2.34,-675), (3000,-39,-2.47,-778), (3250,-44,-2.54,-864), (3500,-50,-2.63,-963), (3750,-55,-2.72,-1066), (4000,-58,-2.75,-1154), (4250,-60,-2.83,-1259), (4500,-60,-3.11,-1467), (4750,-58,-3.31,-1649), (5000,-51,-2.9,-1520), (5250,-40,-1.96,-1079), (5500,-27,-0.84,-481), (5750,-13,0.49,294), (6000,3,1.87,1176), (6250,21,3.31,2163), (6500,41,4.8,3269)],
         }),
    dict(id='0110', label='29x12 3B', D_in=29, P_in=12, blades=3, mass_kg=0.342, ref_engine='Hirth 4201',
         url=MZ + '0110-hirth-motor-4201-mejzlik-29x12-3b-rev01.pdf',
         t={
            0: [(2900,85,3.72,1130), (3500,129,5.53,2026), (4100,179,7.7,3306), (4800,249,10.78,5416), (5400,320,14.04,7939), (6100,424,18.63,11901)],
            20: [(2800,17,2.28,669), (3300,44,3.87,1336), (3900,86,6.28,2566), (4400,128,8.62,3973), (4800,167,10.72,5390), (5000,188,11.85,6206), (5500,246,14.93,8599), (6100,326,19.18,12254)],
            30: [(2600,-14,1.37,374), (3000,-9,1.96,616), (3400,1,2.64,941), (3900,23,4,1632), (4300,50,5.62,2532), (4700,83,7.61,3745), (4800,93,8.17,4105), (5200,132,10.5,5719), (5600,177,13.13,7702), (6100,239,16.79,10723)],
            40: [(3400,-25,2.32,826), (3800,-19,3.09,1230), (4100,-11,3.78,1624), (4400,-1,4.47,2058), (4700,12,5.19,2552), (4800,18,5.56,2794), (5100,37,6.65,3550), (5400,61,8.11,4586), (5700,91,10.01,5974), (6100,137,12.76,8149)],
            50: [(4300,-38,3.86,1736), (4500,-36,4.33,2039), (4700,-32,4.71,2319), (4800,-30,4.95,2487), (5000,-24,5.51,2884), (5200,-17,6.02,3276), (5400,-8,6.59,3724), (5600,2,7.16,4197), (5800,14,7.9,4797), (6100,37,9.28,5931)],
         }),
    dict(id='0111', label='29x13.5 2B Q', D_in=29, P_in=13.5, blades=2, mass_kg=0.285, ref_engine='Hirth 4201',
         url=MZ + '0111-hirth-motor-4201-mejzlik-29x135-2b-q-rev01.pdf',
         t={
            0: [(2900,77,3.01,914), (3500,113,4.44,1629), (4100,158,6.16,2645), (4800,220,8.73,4387), (5400,283,11.23,6349), (6100,367,14.96,9559)],
            20: [(2900,18,1.67,508), (3500,47,3.45,1263), (4100,84,5.5,2361), (4800,136,8.3,4170), (5400,191,11.1,6278), (6100,267,14.94,9542)],
            30: [(2900,-23,-0.41,-124), (3500,-4,0.54,197), (4100,27,2.72,1169), (4800,74,5.81,2920), (5400,123,8.82,4988), (6100,193,12.86,8216)],
            40: [(2900,-36,-0.78,-238), (3500,-45,-1.27,-464), (4100,-35,-1.17,-500), (4800,1,1.33,671), (5400,44,4.54,2568), (6100,107,8.85,5651)],
            50: [(2900,-42,-1.95,-594), (3500,-56,-1.64,-600), (4100,-71,-2.7,-1157), (4800,-70,-2.8,-1409), (5400,-42,-1.52,-858), (6100,11,2.65,1694)],
         }),
    dict(id='0113', label='30x12 2B', D_in=30, P_in=12, blades=2, mass_kg=0.286, ref_engine='Hirth 4201',
         url=MZ + '0113-hirth-motor-4201-mejzlik-30x12-2b-rev01.pdf',
         t={
            0: [(2800,75,3.09,906), (3400,113,4.62,1646), (4000,160,6.63,2775), (4600,216,8.87,4271), (5200,285,11.75,6399), (5900,375,15.65,9670)],
            20: [(2800,17,1.71,501), (3400,47,3.56,1268), (4000,85,5.73,2399), (4600,132,8.25,3974), (5200,189,11.22,6108), (5900,269,15.32,9465)],
            30: [(2800,-7,1.35,397), (3400,-1,0.76,272), (4000,30,3.03,1270), (4600,70,5.79,2789), (5200,121,8.97,4885), (5900,194,13.24,8180)],
            40: [(2800,-16,1.67,488), (3400,-14,2.38,847), (4000,-14,1.12,471), (4600,2,1.4,677), (5200,44,4.76,2591), (5900,108,9.25,5715)],
            50: [(2800,-20,1.4,410), (3400,-24,2.47,878), (4000,-26,3,1255), (4600,-34,1.08,519), (5200,-30,-0.23,-127), (5900,15,3.19,1972)],
         }),
    dict(id='0114', label='30x13 2B EVO', D_in=30, P_in=13, blades=2, mass_kg=0.295, ref_engine='Hirth 4201',
         url=MZ + '0114-hirth-motor-4201-mejzlik-30x13-2b-evo-rev01.pdf',
         t={
            0: [(2800,76,3.07,900), (3400,112,4.57,1627), (4000,158,6.37,2668), (4600,211,8.65,4167), (5200,277,11.3,6154), (5900,362,15,9265)],
            20: [(2800,18,1.67,489), (3400,49,3.63,1293), (4000,88,5.85,2450), (4600,135,8.33,4013), (5200,193,11.34,6174), (5900,272,15.45,9543)],
            30: [(2800,-20,-0.79,-231), (3400,-1,0.59,211), (4000,33,3.16,1322), (4600,76,6.08,2928), (5200,128,9.31,5069), (5900,201,13.58,8389)],
            40: [(2800,-34,-0.68,-200), (3400,-42,-2.08,-740), (4000,-28,-1.31,-551), (4600,7,1.65,793), (5200,53,5.2,2834), (5900,120,9.88,6105)],
            50: [(2800,-40,-1.52,-444), (3400,-49,-0.99,-351), (4000,-66,-3.82,-1601), (4600,-56,-3.11,-1500), (5200,-28,-0.88,-481), (5900,29,3.95,2441)],
         }),
    dict(id='0115', label='30x13 3B EVO', D_in=30, P_in=13, blades=3, mass_kg=0.403, ref_engine='Hirth 4201',
         url=MZ + '0115-hirth-motor-4201-mejzlik-30x13-3b-evo-rev01.pdf',
         t={
            0: [(2800,77,3.16,925), (3400,114,4.7,1673), (4000,161,6.57,2751), (4600,215,8.85,4261), (5200,277,11.61,6323), (5900,366,15.46,9554)],
            20: [(2800,19,1.78,522), (3400,49,3.72,1324), (4000,89,5.95,2494), (4600,137,8.56,4122), (5200,194,11.55,6292), (5900,273,15.64,9661)],
            30: [(2800,-14,0.46,134), (3400,0,0.92,328), (4000,33,3.29,1377), (4600,76,6.13,2955), (5200,127,9.39,5113), (5900,200,13.71,8471)],
            40: [(2800,-30,0.23,67), (3400,-27,0.93,330), (4000,-21,0.26,110), (4600,5,1.9,915), (5200,51,5.33,2904), (5900,117,9.89,6108)],
            50: [(2800,-36,-0.47,-138), (3400,-42,0.53,187), (4000,-43,1.24,519), (4600,-42,0.35,169), (5200,-30,-0.18,-100), (5900,23,4.11,2536)],
         }),
    dict(id='0112', label='30.5x13.5 2B Q', D_in=30.5, P_in=13.5, blades=2, mass_kg=0.293, ref_engine='Hirth 4201',
         url=MZ + '0112-hirth-motor-4201-mejzlik-305x135-2b-q-rev01.pdf',
         t={
            0: [(2800,86,3.47,1017), (3400,128,5.24,1867), (4000,180,7.3,3056), (4600,244,9.91,4773), (5200,316,13.01,7086), (5800,403,16.44,9982)],
            20: [(2800,22,2,585), (3400,56,4.14,1473), (4000,99,6.62,2771), (4600,151,9.51,4582), (5200,215,12.9,7027), (5800,291,16.85,10237)],
            30: [(2800,-24,-0.72,-212), (3400,0,0.75,268), (4000,37,3.53,1479), (4600,84,6.71,3233), (5200,141,10.35,5636), (5800,210,14.5,8806)],
            40: [(2800,-44,-1.74,-509), (3400,-49,-1.92,-683), (4000,-32,-1.57,-659), (4600,5,1.61,774), (5200,55,5.52,3008), (5800,117,9.95,6041)],
            50: [(2800,-52,-3.37,-987), (3400,-71,-3.69,-1315), (4000,-82,-4.06,-1701), (4600,-72,-4.07,-1959), (5200,-38,-1.63,-890), (5800,13,2.89,1753)],
         }),
    dict(id='0164', label='31x12 3B', D_in=31, P_in=12, blades=3, mass_kg=0.412, ref_engine='Zanzottera 305 HS',
         url=MZ + '0164-zanzottera-motor-305hs-mejzlik-31x12-3b.pdf',
         t={
            0: [(2700,101,4.68,1324), (3300,153,7.01,2422), (3900,219,10.22,4173), (4500,298,13.73,6468), (5100,393,18.43,9846), (5700,504,23.51,14032)],
            20: [(2700,25,2.62,741), (3300,68,5.52,1909), (3900,124,8.93,3645), (4500,193,12.93,6092), (5100,276,17.61,9404), (5700,373,23.08,13775)],
            30: [(2700,-16,1.05,296), (3300,1,1.32,456), (3900,48,5.04,2059), (4500,109,9.32,4390), (5100,184,14.22,7592), (5700,274,19.91,11884)],
            40: [(2700,-35,0.67,188), (3300,-33,1.6,552), (3900,-35,-0.82,-336), (4500,12,2.96,1393), (5100,78,8.23,4395), (5700,159,14.13,8434)],
            50: [(2700,-45,-0.43,-122), (3300,-58,0.32,111), (3900,-66,0.11,46), (4500,-76,-2.77,-1306), (5100,-40,-0.88,-472), (5700,29,5.35,3195)],
         }),
    dict(id='0116', label='32x10 2B', D_in=32, P_in=10, blades=2, mass_kg=0.324, ref_engine='Hirth 4201',
         url=MZ + '0116-hirth-motor-4201-mejzlik-32x10-2b-rev01.pdf',
         t={
            0: [(2600,73,2.82,768), (3200,111,4.31,1445), (3800,160,6.24,2481), (4300,207,8.11,3653), (4900,274,10.79,5538), (5500,353,14.1,8120)],
            20: [(2600,6,1,271), (3200,36,3.02,1011), (3800,76,5.35,2131), (4300,116,7.53,3393), (4900,174,10.54,5410), (5500,243,14.08,8108)],
            30: [(2600,-20,0.39,107), (3200,-12,0.64,215), (3800,11,1.92,762), (4300,47,4.42,1992), (4900,98,7.75,3977), (5500,161,11.55,6651)],
            40: [(2600,-32,-0.14,-39), (3200,-35,0.45,150), (3800,-31,0.63,251), (4300,-25,-0.06,-27), (4900,10,2.41,1238), (5500,65,6.55,3773)],
         }),
    dict(id='0117', label='32x12 2B EVO', D_in=32, P_in=12, blades=2, mass_kg=0.316, ref_engine='Hirth 4201',
         url=MZ + '0117-hirth-motor-4201-mejzlik-32x12-2b-evo-rev01.pdf',
         t={
            0: [(2600,88,3.84,1045), (3200,134,5.93,1988), (3800,194,8.51,3384), (4300,252,10.94,4927), (4900,332,14.6,7491), (5500,429,18.94,10906)],
            20: [(2500,12,1.68,441), (3000,41,3.62,1138), (3500,78,5.93,2172), (4000,122,8.53,3572), (4300,153,10.27,4624), (4500,175,11.52,5431), (5000,237,14.96,7834), (5500,309,18.89,10878)],
            30: [(2700,-16,1.03,292), (3100,-7,1.49,483), (3500,11,2.5,917), (3900,41,4.52,1844), (4300,76,6.97,3138), (4700,118,9.69,4770), (5100,165,12.69,6779), (5500,219,16.01,9219)],
            40: [(3100,-34,1.09,355), (3400,-32,1.34,478), (3700,-28,1.58,614), (4000,-18,2.14,896), (4300,-5,2.6,1172), (4600,17,3.87,1864), (4900,45,5.86,3006), (5200,77,8.16,4441), (5500,113,10.76,6199)],
            50: [(3900,-56,1.41,575), (4100,-55,1.61,690), (4300,-53,1.81,816), (4500,-50,1.99,937), (4700,-44,2.31,1139), (4900,-35,2.7,1384), (5100,-25,3.02,1614), (5300,-13,3.36,1867), (5500,2,4.13,2381)],
         }),
    dict(id='0161', label='32x18 2B', D_in=32, P_in=18, blades=2, mass_kg=0.334, ref_engine='Zanzottera 305 HS',
         url=MZ + '0161-zanzottera-motor-305hs-mejzlik-32x18-2b.pdf',
         t={
            0: [(2600,90,4.48,1219), (3200,140,6.86,2298), (3800,199,10.06,4001), (4300,263,12.98,5845), (4900,347,17.63,9046), (5500,451,23.15,13331)],
            20: [(2600,48,4.54,1236), (3200,97,8.07,2703), (3800,155,11.78,4686), (4300,206,14.92,6720), (4900,284,19.7,10106), (5500,380,25.58,14732)],
            30: [(2600,2,1.14,312), (3200,46,5.25,1760), (3800,104,9.98,3972), (4300,162,14.32,6449), (4900,244,20.11,10320), (5500,335,26.21,15095)],
            40: [(2600,-19,0.67,182), (3200,-10,0.57,192), (3800,37,5.19,2064), (4300,92,10.25,4616), (4900,171,16.85,8647), (5500,265,24.22,13952)],
            50: [(2600,-33,-0.19,-52), (3200,-29,1.12,374), (3800,-22,0.2,80), (4300,12,3.27,1473), (4900,83,10.48,5378), (5500,173,18.7,10772)],
         }),
    dict(id='0160', label='33x10 2B', D_in=33, P_in=10, blades=2, mass_kg=0.396, ref_engine='Zanzottera 305 HS',
         url=MZ + '0160-zanzottera-motor-305hs-mejzlik-33x10-2b.pdf',
         t={
            0: [(2600,81,3.26,888), (3200,124,5.02,1682), (3700,168,6.89,2668), (4200,221,8.87,3900), (4300,233,9.45,4257), (4800,294,12.02,6041), (5400,382,15.78,8925)],
            20: [(2600,5,1.59,434), (3200,38,3.55,1191), (3700,74,5.56,2152), (4200,117,7.9,3474), (4300,126,8.41,3787), (4800,179,11.17,5617), (5400,254,15.1,8541)],
            30: [(2600,-23,0.97,265), (3200,-19,1.41,472), (3700,1,2.65,1026), (4200,36,4.71,2073), (4300,45,5.23,2356), (4800,91,7.99,4015), (5400,158,11.99,6783)],
            40: [(3200,-45,0.77,258), (3700,-46,1.33,515), (4200,-37,2.15,945), (4300,-33,2.42,1088), (4800,-7,3.84,1932), (5400,47,7.1,4016)],
         }),
    dict(id='0159', label='34x12 2B', D_in=34, P_in=12, blades=2, mass_kg=0.382, ref_engine='Zanzottera 305 HS',
         url=MZ + '0159-zanzottera-motor-305hs-mejzlik-34x12-2b.pdf',
         t={
            0: [(2500,95,4.1,1074), (3100,146,6.46,2097), (3600,202,8.83,3330), (4100,275,11.67,5011), (4600,342,15,7224), (5200,443,19.91,10844)],
            20: [(2500,18,2.47,648), (3100,59,5.04,1636), (3600,104,7.79,2936), (4100,157,10.97,4708), (4600,222,14.64,7054), (5200,314,19.84,10801)],
            30: [(2500,-15,1.69,443), (3100,-2,2.58,837), (3600,31,4.66,1757), (4100,77,7.56,3244), (4600,134,11.36,5473), (5200,218,16.76,9129)],
            40: [(2500,-30,1.25,326), (3100,-32,2.02,657), (3600,-27,2.74,1031), (4100,-5,4.36,1873), (4600,36,6.96,3354), (5200,107,11.3,6153)],
         }),
]


def _fit(prop) -> tuple:
    """Cubic CT(J), CQ(J) fit through the upper-rpm rows (>= 55 % of the highest tabulated rpm, J <= 0.85).
    Used only to extrapolate beyond the tabulated rpm range (J-similarity; Re/Mach effects ignored)."""
    D = prop["D_in"] * 0.0254
    rmax = max(r[0] for rows in prop["t"].values() for r in rows)
    J, CT, CQ = [], [], []
    for V, rows in prop["t"].items():
        for rpm, T, Q, _ in rows:
            n = rpm / 60.0
            j = V / (n * D)
            if rpm >= 0.55 * rmax and j <= 0.85:
                J.append(j)
                CT.append(T / (RHO_SL * n * n * D ** 4))
                CQ.append(Q / (RHO_SL * n * n * D ** 5))
    return np.polyfit(J, CT, 3), np.polyfit(J, CQ, 3)


def perf(prop, V: float, rpm: float, rho: float = RHO_SL) -> tuple:
    """(thrust N, torque N m, shaft power W, extrapolated?) at flight speed V and rpm.
    Linear in rpm inside each tabulated speed, linear in V between tabulated speeds, J-similarity fit outside the
    tabulated rpm range; thrust and torque scaled with density (same J, Re effects ignored)."""
    t, D = prop["t"], prop["D_in"] * 0.0254
    Vs = sorted(t)
    va = max(v for v in Vs if v <= V)
    vb = min(v for v in Vs if v >= V)
    if "_fit" not in prop:
        prop["_fit"] = _fit(prop)
    ct, cq = prop["_fit"]
    res, extrap = [], False
    for v in (va, vb):
        rows = np.asarray(t[v], float)
        if rows[0, 0] <= rpm <= rows[-1, 0]:
            res.append((np.interp(rpm, rows[:, 0], rows[:, 1]), np.interp(rpm, rows[:, 0], rows[:, 2])))
        else:
            n = rpm / 60.0
            j = v / (n * D)
            res.append((RHO_SL * n * n * D ** 4 * np.polyval(ct, j), RHO_SL * n * n * D ** 5 * np.polyval(cq, j)))
            extrap = True
    w = 0.0 if vb == va else (V - va) / (vb - va)
    T = ((1 - w) * res[0][0] + w * res[1][0]) * rho / RHO_SL
    Q = ((1 - w) * res[0][1] + w * res[1][1]) * rho / RHO_SL
    return float(T), float(Q), float(Q * 2 * math.pi * rpm / 60.0), extrap


def q_engine(rpm: float, scale: float = 1.0) -> float:
    return scale * float(np.interp(rpm, ENG_RPM, ENG_Q))


def tip_mach(prop, rpm: float, V: float = 0.0) -> float:
    D = prop["D_in"] * 0.0254
    return math.hypot(math.pi * D * rpm / 60.0, V) / A_SL


def thrust_required(V: float, CD0: float = DRAG["CD0"], rho: float = RHO_SL) -> float:
    q = 0.5 * rho * V * V
    W = DRAG["mass_kg"] * G0
    return q * DRAG["S_m2"] * CD0 + W * W / (q * DRAG["S_m2"] * math.pi * DRAG["e"] * DRAG["AR"])


def _solve(f, lo, hi):
    from scipy.optimize import brentq
    flo, fhi = f(lo), f(hi)
    if flo * fhi > 0:
        return None
    return brentq(f, lo, hi, xtol=1.0)


def wot_point(prop, V: float, scale: float = 1.0) -> dict:
    """Fixed-pitch WOT equilibrium: prop torque = engine torque (L 275 EF curve x scale), 4000-7500 rpm."""
    f = lambda n: perf(prop, V, n)[1] - q_engine(n, scale)
    n = _solve(f, ENG_RPM[0], ENG_RPM_MAX)
    if n is None:
        hi = perf(prop, V, ENG_RPM_MAX)[1] < q_engine(ENG_RPM_MAX, scale)
        n = ENG_RPM_MAX if hi else ENG_RPM[0]
        note = "prop underloads the engine: rpm limited at 7500 (governor/throttle)" if hi else \
            "prop overloads the engine: equilibrium below 4000 rpm (outside the published curve)"
    else:
        note = None
    T, Q, P, ex = perf(prop, V, n)
    out = {"rpm": round(n), "thrust_N": round(T), "shaft_power_W": round(P), "tip_mach_helical": round(tip_mach(prop, n, V), 3),
           "extrapolated_beyond_table": ex}
    if V > 0:
        out["efficiency"] = round(T * V / P, 3) if P > 0 else None
    if note:
        out["note"] = note
    return out


def cruise_point(prop, V: float, Treq: float) -> dict:
    f = lambda n: perf(prop, V, n)[0] - Treq
    n = _solve(f, 2500.0, ENG_RPM_MAX)
    if n is None:
        return {"thrust_required_N": round(Treq, 1), "note": "required thrust not reached between 2500 and 7500 rpm"}
    T, Q, P, ex = perf(prop, V, n)
    D = prop["D_in"] * 0.0254
    return {"thrust_required_N": round(Treq, 1), "rpm": round(n), "advance_ratio_J": round(V / (n / 60 * D), 3),
            "shaft_power_W": round(P), "efficiency": round(T * V / P, 3), "tip_mach_helical": round(tip_mach(prop, n, V), 3),
            "throttle_torque_fraction": round(Q / q_engine(n), 2), "extrapolated_beyond_table": ex}


def run_props() -> dict:
    res = {}
    for p in MEJZLIK:
        e = {"label": f"Mejzlik {p['label']}", "diameter_m": round(p["D_in"] * 0.0254, 4),
             "pitch_nominal_m": round(p["P_in"] * 0.0254, 4), "blades": p["blades"], "mass_kg": p["mass_kg"],
             "source": p["url"], "tag": "estimate",
             "basis": "operating points derived from the Mejzlik manufacturer table (tag manufacturer) and the "
                      "L 275 EF datasheet WOT torque curve (tag datasheet)",
             "static_wot_L275EF": wot_point(p, 0.0),
             "static_wot_20kW_class": wot_point(p, 0.0, scale=20000.0 / 18870.0),
             "wot_at_20_m_s": wot_point(p, 20.0), "wot_at_30_m_s": wot_point(p, 30.0),
             "wot_at_40_m_s": wot_point(p, 40.0),
             "cruise_partial_throttle": {f"V_{V:.0f}_m_s": cruise_point(p, V, thrust_required(V)) for V in (30.0, 35.0, 40.0)}}
        res[p["id"]] = e
    # screening: static match 5000-6500 rpm, static tip Mach <= 0.72, WOT rpm at 40 m/s <= 7500 (not limited)
    ok = []
    for pid, e in res.items():
        s, w40 = e["static_wot_L275EF"], e["wot_at_40_m_s"]
        crz = [c.get("efficiency") for c in e["cruise_partial_throttle"].values()]
        if None in crz:
            continue
        c30 = e["cruise_partial_throttle"]["V_30_m_s"]
        passed = (5000 <= s["rpm"] <= 6500 and s["tip_mach_helical"] <= 0.76 and "note" not in s and "note" not in w40
                  and c30.get("rpm", 0) >= 3500)
        e["screen_pass"] = bool(passed)
        e["cruise_efficiency_mean_30_40"] = round(float(np.mean(crz)), 3)
        if passed:
            ok.append((e["cruise_efficiency_mean_30_40"], s["thrust_N"], pid))
    ok.sort(reverse=True)
    return {"screening_rule": "static WOT equilibrium 5000-6500 rpm, static tip Mach <= 0.76, WOT at 40 m/s below "
                              "7500 rpm (prop loads the engine in flight), cruise rpm at 30 m/s >= 3500; ranked by mean "
                              "partial-throttle efficiency at 30/35/40 m/s",
            "ranking": [{"id": pid, "label": res[pid]["label"], "cruise_efficiency_mean_30_40": eff, "static_thrust_N": T}
                        for eff, T, pid in ok],
            "props": res}


def prop_tables() -> dict:
    """Raw Mejzlik tables (for later performance modelling), rows [rpm, thrust_N, torque_Nm, power_W]."""
    return {p["id"]: {"label": f"Mejzlik {p['label']}", "source": p["url"], "tag": "manufacturer",
                      "reference_engine_on_sheet": p["ref_engine"],
                      "rows_rpm_thrust_N_torque_Nm_power_W": {f"V_{v}_m_s": [list(r) for r in p["t"][v]] for v in sorted(p["t"])}}
            for p in MEJZLIK}


# Falcon carbon gas propellers, measured static rpm and thrust on hobby engines (Falcon Propeller Test Chart, 2-blade;
# columns mapped from the PDF word positions).  (label, D_in, P_in, engine, rpm, thrust_kgf, Mejzlik id of same size)
FALCON_URL = "https://www.falconpropellers.com/wp-content/uploads/2020/04/Falcon-Propeller-Test-Chart.pdf"
FALCON = [
    ("26x12", 26, 12, "DA-120", 6840, 30.1, "0100"), ("28x10", 28, 10, "DA-120", 6550, 31.0, "0127"),
    ("28x12", 28, 12, "DA-120", 6290, 32.5, "0097"), ("30x12", 30, 12, "DLE-170", 6100, 37.2, "0113"),
    ("30x13", 30, 13, "DA-200", 6250, 41.8, "0114"), ("32x10", 32, 10, "DA-200", 6150, 40.9, "0116"),
    ("32x12", 32, 12, "DA-200", 5670, 40.6, "0117"), ("32x12", 32, 12, "DLE-222", 5820, 42.5, "0117"),
    ("34x12", 34, 12, "DA-200", 5280, 42.0, "0159"), ("34x12", 34, 12, "DLE-222", 5530, 46.0, "0159"),
]


def falcon_cross_check() -> dict:
    """Measured Falcon static thrust vs Mejzlik table/J-similarity static thrust of the same nominal size and rpm."""
    byid = {p["id"]: p for p in MEJZLIK}
    rows, ratios = [], []
    for lab, D, P, eng, rpm, kgf, mid in FALCON:
        T_mz = perf(byid[mid], 0.0, rpm)[0]
        T_f = kgf * G0
        ratios.append(T_f / T_mz)
        rows.append({"size_in": lab, "falcon_engine": eng, "rpm": rpm, "falcon_thrust_N": round(T_f), "mejzlik_prop": byid[mid]["label"],
                     "mejzlik_thrust_N_same_rpm": round(T_mz), "ratio_falcon_over_mejzlik": round(T_f / T_mz, 3)})
    return {"source": FALCON_URL, "tag": "manufacturer",
            "note": "Falcon values are measured static rpm/thrust of Falcon props on the named engines (test conditions not "
                    "stated). Different blade designs of the same nominal size, so the ratio mixes design and "
                    "simulation differences.",
            "rows": rows, "ratio_mean": round(float(np.mean(ratios)), 3), "ratio_min": round(float(np.min(ratios)), 3),
            "ratio_max": round(float(np.max(ratios)), 3)}


def validation() -> dict:
    """NeuralFoil vs published wind-tunnel results."""
    def cm_at_cl0(p):
        cl, cm = p["CL"], p["CM"]
        i = int(np.argmax(cl))
        o = np.argsort(cl[: i + 1])
        return float(np.interp(0.0, cl[: i + 1][o], cm[: i + 1][o]))

    def cd_at(p, c):
        cl, cd = p["CL"], p["CD"]
        i = int(np.argmax(cl))
        o = np.argsort(cl[: i + 1])
        return float(np.interp(c, cl[: i + 1][o], cd[: i + 1][o]))

    out = {}
    _, P = load("nlf416")
    kaf, _ = kulfan("nlf416", P)
    r = {}
    for case in ("ncrit9", "tripped"):
        pp = polar(kaf, 3.0e6, case)
        m = metrics(pp)
        r[case] = {"cl_max": m["cl_max"], "alpha_zero_lift_deg": m["alpha_zero_lift_deg"], "cm_c4_at_cl_0": round(cm_at_cl0(pp), 4)}
    out["nlf416_Re_3e6"] = {
        "neuralfoil": {"tag": "estimate", "source": NF_URL, **r},
        "experiment": {"cl_max": 1.69, "cl_max_transition_fixed": "no significant change", "alpha_zero_lift_deg": -3.8,
                       "cm_c4_at_cl_0": -0.09, "tag": "paper",
                       "source": "https://ntrs.nasa.gov/api/citations/19810015487/downloads/19810015487.pdf",
                       "note": "NASA TP-1861 (Somers 1981), Langley LTPT, M 0.1; roughness at 0.075c both surfaces"}}
    _, P = load("ls417")
    kaf, _ = kulfan("ls417", P)
    r = {}
    for Re in (2.0e6, 6.0e6):
        pp = polar(kaf, Re, "tripped")
        r[_rekey(Re)] = {"l_over_d_at_cl_1p0": round(1.0 / cd_at(pp, 1.0), 1), "cl_max": metrics(pp)["cl_max"]}
    out["ls417_tripped"] = {
        "neuralfoil": {"tag": "estimate", "source": NF_URL, **r},
        "experiment": {"l_over_d_at_cl_1p0_Re_2e6_to_6e6": [65, 85], "cl_max": "greater than 2.0 (Re 2-20e6 range)",
                       "tag": "paper", "source": "https://ntrs.nasa.gov/citations/19740003708",
                       "note": "NASA TN D-7428 (McGhee & Beasley 1973) abstract; transition fixed in those tests"}}
    return out


# =====================================================================================================================
# YAML output
# =====================================================================================================================
def build() -> dict:
    af = run_airfoils()
    return {
        "generated": {
            "by": "ucav250/data/research/aero_polars.py",
            "date": _dt.date.today().isoformat(),
            "tag": "estimate",
            "source": NF_URL,
            "method": (f"NeuralFoil {MODEL} on the aerosandbox Kulfan (CST) fit of the coordinates; alpha -4..16 deg "
                       f"step 0.25 (extended to 22 deg only to locate cl_max and the post-stall ratio); cases "
                       f"{list(CASES)}; cl_cruise {CL_CRUISE}, cl_loiter {CL_LOITER}; drag bucket = contiguous cl range "
                       f"with cd <= {BUCKET_FACTOR} x cd_min; Re keys are chord Reynolds numbers; Mach 0."),
            "cases": CASES,
        },
        "summary_Re_1.5e6": {"tag": "estimate", "source": NF_URL, "rows": summary_table(af, "Re_1.5e6")},
        "summary_Re_0.8e6": {"tag": "estimate", "source": NF_URL, "rows": summary_table(af, "Re_0.8e6")},
        "airfoil_polars": af,
        "coordinate_source_check_Re_1.5e6_ncrit9": source_check(),
        "validation_vs_wind_tunnel": validation(),
        "propeller_operating_points": {
            "tag": "estimate",
            "source": "https://www.mejzlik.eu/propulsion-system-data",
            "method": ("Mejzlik tables (ISA sea level) interpolated linearly in rpm and flight speed; outside the "
                       "tabulated rpm range a cubic CT(J)/CQ(J) fit of the upper-rpm rows is used (flagged). WOT = "
                       "prop torque equals the L 275 EF datasheet WOT torque (engine.yaml); '20kW_class' scales that "
                       "torque by 20/18.87. Cruise = rpm at which thrust equals the estimated thrust required, "
                       "efficiency = T V / P (isolated propeller; no installation, blockage or pusher-wake losses)."),
            "drag_estimate_for_thrust_required": {
                **DRAG, "tag": "estimate", "source": "ucav250/data/research/comparables.yaml",
                "basis": "MTOW, S and AR = comparables.yaml recommended_ranges nominals; CD0 0.035 and e 0.75 as in its "
                         "consistency check; D = q S CD0 + W^2/(q S pi e AR), ISA sea level",
                "thrust_required_N": {f"V_{V:.0f}_m_s": round(thrust_required(V), 1) for V in (25.0, 30.0, 35.0, 40.0, 45.0)},
                "thrust_required_N_CD0_band": {f"V_{V:.0f}_m_s": [round(thrust_required(V, c), 1) for c in CD0_BAND]
                                               for V in (30.0, 35.0, 40.0)},
            },
            **run_props(),
            "cross_check_falcon_measured_static": falcon_cross_check(),
        },
        "propeller_tables_mejzlik": prop_tables(),
    }


def to_yaml(data: dict) -> str:
    import yaml

    class Dumper(yaml.SafeDumper):
        pass

    def flow_list(d, v):
        return d.represent_sequence("tag:yaml.org,2002:seq", v, flow_style=not any(isinstance(x, dict) for x in v))

    def maybe_flow_dict(d, v):
        flow = all(not isinstance(x, (dict, list, tuple)) or
                   (isinstance(x, (list, tuple)) and len(x) <= 2 and not any(isinstance(y, (list, dict)) for y in x))
                   for x in v.values())
        return d.represent_mapping("tag:yaml.org,2002:map", v, flow_style=flow)
    Dumper.ignore_aliases = lambda self, data: True
    Dumper.add_representer(list, flow_list)
    Dumper.add_representer(tuple, flow_list)
    Dumper.add_representer(dict, maybe_flow_dict)
    return yaml.dump(data, Dumper=Dumper, sort_keys=False, width=160, allow_unicode=False)


def update_yaml(block: str) -> None:
    text = AERO_YAML.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        raise SystemExit(f"markers not found in {AERO_YAML}")
    AERO_YAML.write_text(pat.sub(lambda _m: f"{BEGIN}\n{block.rstrip()}\n{END}", text))
    print(f"updated generated block in {AERO_YAML}", file=sys.stderr)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--download", action="store_true", help="fetch and convert the UIUC coordinate files")
    ap.add_argument("--update-yaml", action="store_true", help="replace the generated block inside aero.yaml")
    ap.add_argument("--out", type=Path, help="also write the generated YAML block to this file")
    args = ap.parse_args(argv)
    if args.download:
        download([f for f, _, s, _ in WING + TAIL if s == "uiuc"])
    block = to_yaml(build())
    if args.out:
        args.out.write_text(block)
    if args.update_yaml:
        update_yaml(block)
    if not (args.out or args.update_yaml):
        print(block)


if __name__ == "__main__":
    main()
